# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure
---

email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-express
    software_stack: nodejs
    nodejs_app_git_clone: false # Sorry, this variable should be renamed
    folder:
      dest: /app/gpii-express
      src: .
    run_in: fedora
    deploy: false
    setup:
      - npm install
    test_cmds:
      - npm test

